# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 174f4aca26e71f1a6cafc7f13163050a2e55a729c8261aa34a13fa4d3e43c28ef007c2a2d031b40882e41882b5fff1c53d2b8b8dc779cd6cc84bad44e2079133

test:
  secret_key_base: 7bc09defeddbad27c8a33a722e920eae52baa82572074f91ab8a38c493aa9c02052be3ca23201c0efd2164d641736550dc4bbc2192eba91b026aa85d60ffcc02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
